/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Menu;

import Fornecedores.Cadastro_de_Fornecedores;
import Fornecedores.Fornecedor;
import Notas.CadastrarNotas;
import Notas.EditarNota;
import Notas.Tela_Nota;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Carina
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private String ConteudoDApesquisa_da_tabela;

    public String getConteudoDApesquisa_da_tabela() {
        return ConteudoDApesquisa_da_tabela;
    }

    public void setConteudoDApesquisa_da_tabela(String ConteudoDApesquisa_da_tabela) {
        this.ConteudoDApesquisa_da_tabela = ConteudoDApesquisa_da_tabela;
    }
    /**
     * Creates new form nasn
     */
    public MenuPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela_ContasApagar1 = new javax.swing.JTable();
        button_editarNota = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        intemMenu_ContasAPagar = new javax.swing.JMenu();
        intemMenu_Sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        intemMenu_Notas = new javax.swing.JMenuItem();
        intemMenu_CadastrarNotas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        intemMenu_Fornecedor = new javax.swing.JMenuItem();
        intemMenu_CadastrarFornecedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jButton1.setText("Finalizar");

        Tabela_ContasApagar1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3"
            }
        ));
        jScrollPane2.setViewportView(Tabela_ContasApagar1);

        button_editarNota.setText("Editar");
        button_editarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editarNotaActionPerformed(evt);
            }
        });

        intemMenu_ContasAPagar.setText("Contas a Pagar");

        intemMenu_Sair.setText("Sair");
        intemMenu_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intemMenu_SairActionPerformed(evt);
            }
        });
        intemMenu_ContasAPagar.add(intemMenu_Sair);

        jMenuBar1.add(intemMenu_ContasAPagar);

        jMenu2.setText("Notas");

        intemMenu_Notas.setText("Tabela de Notas");
        intemMenu_Notas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intemMenu_NotasActionPerformed(evt);
            }
        });
        jMenu2.add(intemMenu_Notas);

        intemMenu_CadastrarNotas.setText("Cadastrar");
        intemMenu_CadastrarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intemMenu_CadastrarNotasActionPerformed(evt);
            }
        });
        jMenu2.add(intemMenu_CadastrarNotas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Fornecedor");

        intemMenu_Fornecedor.setText("Tabela Fornecedor");
        intemMenu_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intemMenu_FornecedorActionPerformed(evt);
            }
        });
        jMenu3.add(intemMenu_Fornecedor);

        intemMenu_CadastrarFornecedor.setText("Cadastrar");
        intemMenu_CadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intemMenu_CadastrarFornecedorActionPerformed(evt);
            }
        });
        jMenu3.add(intemMenu_CadastrarFornecedor);

        jMenuBar1.add(jMenu3);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(button_editarNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(button_editarNota))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void intemMenu_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intemMenu_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_intemMenu_SairActionPerformed

    private void intemMenu_NotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intemMenu_NotasActionPerformed
        new Tela_Nota().setVisible(true);
    }//GEN-LAST:event_intemMenu_NotasActionPerformed

    private void intemMenu_CadastrarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intemMenu_CadastrarNotasActionPerformed
        new CadastrarNotas().setVisible(true);
    }//GEN-LAST:event_intemMenu_CadastrarNotasActionPerformed

    private void intemMenu_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intemMenu_FornecedorActionPerformed
        new Fornecedor().setVisible(true);
    }//GEN-LAST:event_intemMenu_FornecedorActionPerformed

    private void intemMenu_CadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intemMenu_CadastrarFornecedorActionPerformed
        new Cadastro_de_Fornecedores().setVisible(true);
    }//GEN-LAST:event_intemMenu_CadastrarFornecedorActionPerformed

    private void button_editarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_editarNotaActionPerformed
    Tabela_ContasApagar1.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
				String ConteudoDApesquisa_da_tabela = (String) Tabela_ContasApagar1.getModel().getValueAt(
						Tabela_ContasApagar1.getSelectedRow(), Tabela_ContasApagar1.getSelectedColumn());
			}
                        });
         new EditarNota().setVisible(true);
    }//GEN-LAST:event_button_editarNotaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela_ContasApagar1;
    private javax.swing.JToggleButton button_editarNota;
    private javax.swing.JMenuItem intemMenu_CadastrarFornecedor;
    private javax.swing.JMenuItem intemMenu_CadastrarNotas;
    private javax.swing.JMenu intemMenu_ContasAPagar;
    private javax.swing.JMenuItem intemMenu_Fornecedor;
    private javax.swing.JMenuItem intemMenu_Notas;
    private javax.swing.JMenuItem intemMenu_Sair;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
